name: Run typos to check spelling

on: [push]

jobs:
  run:
    name: Spell Check with push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Actions Repository
      uses: actions/checkout@v2

    - name: Check spelling of file.txt
      uses: crate-ci/typos@master